audio:
  rate: 16000  # Sample rate (Hz)
  chunk: 4096  # Buffer size (increased for longer recordings)
  channels: 1  # Mono audio
  max_duration: 0  # Maximum recording duration in seconds (0 for unlimited, was 30)

whisper:
  model_size: "medium"  # Changed to medium for better accuracy
  device: "auto"  # Options: cpu, cuda, auto
  compute_type: "float32"  # Options: float16, float32, int8
  language: "en"  # Language code (leave empty for auto-detect)
  models_dir: "~/.cache/whisper"  # Directory to store models

hotkeys:
  method: "external"  # Options: external, direct, disabled
  external_script: "./toggle-stt.sh"  # Path to toggle script (relative to hyprstt directory)
  toggle_recording: ["CTRL", "ALT", "SPACE"]  # Hotkey for direct method (avoid function keys)
  use_hypr_dispatch: false  # Use Hyprland IPC integration (for direct method only)

ui:
  notifications: true  # Enable desktop notifications
  notification_timeout: 2  # Notification display time in seconds
  # visual_indicator has been removed for stability - notifications provide feedback